SELECT TOP 200 [flight_num]
	, [year]
	, [airline_carrier]
	, [departure_time]
	, [departure_city]
	, [arrival_time]
	, [arrival_city]
	, [terminal]
	, [pilot_id]
	, [carry_on_bag_fee]
	, [plane_manufacturer]
	, [model_num]
	, [num_of_seats]
	, [material]
FROM [AirportData].[dbo].[airport_data_flat_table]